### ISSUE TITLE
Readme Error

### ISSUE THREAD

**Issue by michaelpelletier** [sbatson5/movie_wager_api#9]
I don't have permission to push to this so I can't open a PR, but in the readme:

`Copy the dev.secret.example.exs to dev.secret.exz file and uncomment out the block of code. Enter in your postgres credentials:`

Should be .exs, not .exz

**Comment by sbatson5** [comment]
Yeah, I caught that in this PR: https://github.com/sbatson5/movie_wager_api/pull/8.

Also, added you as a collaborator
